// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ActionNONE = 0
	ActionGET = 1
	ActionSET = 2
	ActionNEW = 3
	ActionAPPEND = 4
	ActionREPLACE = 5
	ActionUPDATE = 6
	ActionDELETE = 7
)

var EnumNamesAction = map[int]string{
	ActionNONE:"NONE",
	ActionGET:"GET",
	ActionSET:"SET",
	ActionNEW:"NEW",
	ActionAPPEND:"APPEND",
	ActionREPLACE:"REPLACE",
	ActionUPDATE:"UPDATE",
	ActionDELETE:"DELETE",
}

