// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	CmdSUB = 0
	CmdUNSUB = 1
	CmdSYN = 2
)

var EnumNamesCmd = map[int]string{
	CmdSUB:"SUB",
	CmdUNSUB:"UNSUB",
	CmdSYN:"SYN",
}

