// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	CmdNONE = 0
	CmdSUB = 1
	CmdUNSUB = 2
	CmdSYN = 3
	CmdREADY = 4
)

var EnumNamesCmd = map[int]string{
	CmdNONE:"NONE",
	CmdSUB:"SUB",
	CmdUNSUB:"UNSUB",
	CmdSYN:"SYN",
	CmdREADY:"READY",
}

