// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ErrNO_HANDLER = 0
	ErrINVALID = 1
	ErrREMOTE = 2
	ErrTIMEOUT = 3
)

var EnumNamesErr = map[int]string{
	ErrNO_HANDLER:"NO_HANDLER",
	ErrINVALID:"INVALID",
	ErrREMOTE:"REMOTE",
	ErrTIMEOUT:"TIMEOUT",
}

