// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	ErrNONE = 0
	ErrNO_HANDLER = 1
	ErrINVALID = 2
	ErrREMOTE = 3
	ErrTIMEOUT = 4
)

var EnumNamesErr = map[int]string{
	ErrNONE:"NONE",
	ErrNO_HANDLER:"NO_HANDLER",
	ErrINVALID:"INVALID",
	ErrREMOTE:"REMOTE",
	ErrTIMEOUT:"TIMEOUT",
}

