// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	MsgTypeNONE = 0
	MsgTypePEER = 1
	MsgTypeMULT = 2
	MsgTypeQUEUE = 3
	MsgTypeCMD = 4
)

var EnumNamesMsgType = map[int]string{
	MsgTypeNONE:"NONE",
	MsgTypePEER:"PEER",
	MsgTypeMULT:"MULT",
	MsgTypeQUEUE:"QUEUE",
	MsgTypeCMD:"CMD",
}

