// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	MsgTypeNONE = 0
	MsgTypeSINGLE = 1
	MsgTypeCAST = 2
	MsgTypeQUEUE = 3
	MsgTypeCMD = 4
)

var EnumNamesMsgType = map[int]string{
	MsgTypeNONE:"NONE",
	MsgTypeSINGLE:"SINGLE",
	MsgTypeCAST:"CAST",
	MsgTypeQUEUE:"QUEUE",
	MsgTypeCMD:"CMD",
}

