// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	MsgTypePEER = 0
	MsgTypeMULT = 1
	MsgTypeQUEUE = 2
	MsgTypeCMD = 3
)

var EnumNamesMsgType = map[int]string{
	MsgTypePEER:"PEER",
	MsgTypeMULT:"MULT",
	MsgTypeQUEUE:"QUEUE",
	MsgTypeCMD:"CMD",
}

