// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	StsNONE = 0
	StsERROR = 1
	StsREQ = 2
	StsREP = 3
	StsCANCEL = 4
	StsSUCCESS = 5
)

var EnumNamesSts = map[int]string{
	StsNONE:"NONE",
	StsERROR:"ERROR",
	StsREQ:"REQ",
	StsREP:"REP",
	StsCANCEL:"CANCEL",
	StsSUCCESS:"SUCCESS",
}

