// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	StsERROR = 0
	StsREQ = 1
	StsREP = 2
	StsCANCEL = 3
	StsSUCCESS = 4
)

var EnumNamesSts = map[int]string{
	StsERROR:"ERROR",
	StsREQ:"REQ",
	StsREP:"REP",
	StsCANCEL:"CANCEL",
	StsSUCCESS:"SUCCESS",
}

