// automatically generated by the FlatBuffers compiler, do not modify

package IndisMQ

const (
	StsNONE = 0
	StsERROR = 1
	StsREQ = 2
	StsREP = 3
	StsSEQ = 4
	StsCANCEL = 5
	StsSUCCESS = 6
	StsACK = 7
)

var EnumNamesSts = map[int]string{
	StsNONE:"NONE",
	StsERROR:"ERROR",
	StsREQ:"REQ",
	StsREP:"REP",
	StsSEQ:"SEQ",
	StsCANCEL:"CANCEL",
	StsSUCCESS:"SUCCESS",
	StsACK:"ACK",
}

